theme = "Scenic"
# Edit the following values between the quotation marks ("")
baseURL = "http://localhost:1313" # Your site url
languageCode = "en_US" # Your site's main language
title = "The Hugo Scenic" # Your site's title

[taxonomies] 
tag = "tags" 
category = "categories" 
article = "articles"
#TAXONOMY_NAME_SINGLE = "PLURAL" 
# Add your own taxonomies 
[params]
# AMP COMPONENTS #
  ampInstagram = "true"
  ampCarousel = "true"
  ampAccordion = "true"
  ampSocialShare = "true"
  ampGoogleAnalytics = "true"
# END AMP MODULES #

# FONTS #

 ## GOOGLE FONTS ##
   IwantGoogleFonts = "true" # If you don't want change true to false inside the quotes.
   NameOfGoogleFont = "Raleway" # Name of the Google font. For examples see the docs.
   NameOfGoogleFontFamily = "Raleway" # Name of the Google font family. For examples see the docs.
 ## END GOOGLE FONTS ##

 ## CUSTOM FONTS ##
   IwantCustomFonts = "false" # If you want to use custom fonts set IwantGoogleFonts to false and IwantCustomFonts to true..
   FontsWOFF = "hachimarupop-regular-webfont.woff"
   FontsWOFF2 = "hachimarupop-regular-webfont.woff2"
 ## END CUSTOM FONTS ##

# END FONTS #

# COLORS #
 ChoosePalette = "dark" # light or dark
 ## LIGHT COLOR PALETTE ##
  BrandColorLP = "#264653" # Initial Value #264653 Social Share Icons, sidebar menu, Sidebar Menu Icon, Site title
  BackgroundColorLP = "#f8f8ff" # Initial Value #f8f8ff Header Background, Main background
  FontsColorLP = "#000013" # Initial Value #000013 Font Color.
  MenuFontsColorLP = "#f8f8ff" # Initial Value #f8f8ff
  AttentionColorLP = "#400000" # 
 ## END LIGHT COLOR PALETTE

 ## DARK COLOR PALETTE ##
  BrandColorDP = "#bcccdc" # Initial Value #264653 Social Share Icons, sidebar menu, Sidebar Menu Icon, Site title
  BackgroundColorDP = "#121212" # Initial Value #f8f8ff Header Background, Main background
  FontsColorDP = "#bcccdc" # Initial Value #000013 Font Color.
  MenuFontsColorDP = "#171f24" # Initial Value #f8f8ff
  AttentionColorDP = "#ff6700" # 
 ## END DARK COLOR PALETTE ##
# END COLORS #

# SOCIAL SHARE #
  ShareOnTwitter = "true"
  ShareOnFacebook = "true"
  ShareOnLinkedIn = "true"
  ShareWithSystem = "true"
  ShareOnPinterest = "true"
  ShareOnTumblr = "true"
  ShareWithEmail = "true"
  ShareOnWhatsapp = "true"
  ShareOnLine = "true"
# END SOCIAL SHARE #

# FOLLOW ON SOCIAL #
  twitter = "https://www.twitter.com/AnimoPhoenicus"
  facebook = "https://www.facebook.com"
  instagram = "https://www.instagram.com"
  pinterest = "https://www.pinterest.com"
  youtube = "https://www.pinterest.com"
  reddit = "https://www.reddit.com"
  tik-tok = "https://www.tik-tok.com"
  snapchat = "https://www.snapchat.com"
  github = "https://www.github.com"
  gitlab = "https://www.gitlab.com"
# END FOLLOW ON SOCIAL #

# FOOTER COPYRIGHT #
  Copyright = ""

### EDIT BELOW THIS POINT ONLY IF YOU KNOW WHAT ARE YOU DOING ###
